data:
  data_dir: /usr/workspace/hip/ML4Jets/regression_images/
  num_train_files: 40
  num_folds: 4
  fold_ind: 0
  batch_size: 1024
  shuffle: False
  num_procs: 16
  preprocess: True
  output_dir: preprocessed_data/
  already_preprocessed: True
model:
  block_type: graphnet
  num_blocks: 3
  num_layers: 2
  latent_size: 16
  concat_input: True
  reducer: mean
  edge_block_opt:
    use_edges: True
    use_receiver_nodes: True
    use_sender_nodes: True
    use_globals: True
  node_block_opt:
    use_received_edges: True
    use_sent_edges: False
    use_nodes: True
    use_globals: True
  global_block_opt:
    use_edges: False
    use_nodes: True
    use_globals: True
training:
  epochs: 10
  learning_rate: 1.e-3
  alpha: 1
  save_dir: results/
  gpu: 0
  log_freq: 1
