data:
  batch_size: 1024
  data_dir: /usr/workspace/hip/ML4Jets/regression_images/
  fold_ind: 0
  num_folds: 4
  num_procs: 16
  num_train_files: 40
  k: 4
  output_dir: /p/vast1/karande1/heavyIon/data/preprocessed_data/
  preprocess: true
  already_preprocessed: True
  shuffle: false
  use_xyz: True
model:
  block_type: graphnet
  concat_input: True
  edge_block_opt:
    use_edges: true
    use_globals: true
    use_receiver_nodes: true
    use_sender_nodes: true
  global_block_opt:
    use_edges: false
    use_globals: true
    use_nodes: true
  latent_size: 64
  node_block_opt:
    use_globals: true
    use_nodes: true
    use_received_edges: true
    use_sent_edges: false
  num_blocks: 4
  num_layers: 4
  reducer: mean
training:
  alpha: 0
  epochs: 10
  learning_rate: 0.001
  save_dir: /p/vast1/karande1/heavyIon/results/
  gpu: 0
  log_freq: 100
